#!/bin/bash

python figure_2_supplementary_3c.py

python figure_3c.py
python figure_3d.py

python figure_3_supplementary_1e.py

python figure_4a.py
python figure_4b-c.py
python figure_4d-e.py

python figure_4_supplementary_1a.py
python figure_4_supplementary_1b.py
python figure_4_supplementary_1c.py

python figure_4_supplementary_2.py

python figure_4_supplementary_3a.py
python figure_4_supplementary_3b.py
python figure_4_supplementary_4.py

python figure_5a.py
python figure_5b.py
python figure_5c.py
python figure_5d.py

